Create the `bookrecommendation` microservice:

`mn create-app example.micronaut.bookrecommendation.bookrecommendation`

The previous command creates a folder named `bookrecommendation` and a Micronaut app inside it with
default package: `example.micronaut.bookrecommendation`.

Create an interface to map operations with `bookcatalogue` and a Micronaut Declarative HTTP Client to consume it.

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueOperations.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueOperations.java[]
----

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueClient.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueClient.java[tag=packageandimports]

include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueClient.java[tag=harcoded]
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookCatalogueClient.java[tag=clazz]
----

<1> Use `@Client` to use https://docs.micronaut.io/latest/guide/index.html#clientAnnotation[declarative HTTP Clients]

The client returns a POJO. Create it in the `bookrecommendation`:
[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/Book.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/Book.java[]
----

Create an interface to map operations with `bookinventory` and a Micronaut Declarative HTTP Client to consume it.

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryOperations.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryOperations.java[]
----

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryClient.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryClient.java[tag=packageandimports]

include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryClient.java[tag=harcoded]
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookInventoryClient.java[tag=clazz]
----

<1> Use `@Client` to use https://docs.micronaut.io/latest/guide/index.html#clientAnnotation[declarative HTTP Clients]

Create a Controller which injects both clients.

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookController.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookController.java[]
----

<1> The class is defined as a controller with the http://docs.micronaut.io/latest/api/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/books`
<2> Constructor injection
<3> The `@Get` annotation is used to map the index method to `/books` requests that use an HTTP GET.

The previous controller returns a `Flowable<BookRecommendation>`. Create the `BookRecommendation` POJO:

[source,java]
.bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookRecommendation.java
----
include::{sourceDir}/bookrecommendation/src/main/java/example/micronaut/bookrecommendation/BookRecommendation.java[]
----

`BookCatalogueClient` and `BookInventoryClient` will fail to consume the `bookcatalogue` and `bookinventory` during the tests phase.

Using the https://docs.micronaut.io/latest/guide/index.html#clientFallback[@Fallback] annotation you can declare a fallback implementation of a client that will be picked up and used once all possible retries have been exhausted

Create `@Fallback` alternatives in the `test` classpath.

[source,java]
.bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookInventoryClientStub.java
----
include::{sourceDir}/bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookInventoryClientStub.java[]
----

<1> Make this fallback class to be effective only when the micronaut environment __TEST__ is active
<2> Here we arbitrarily decided that if everything else fails, that book's `stock` would be true
<3> Similarly, we decided that other book's `stock` method would be false
<4> Finally, any other book will have their `stock` method return an empty value


[source,java]
.bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookCatalogueClientStub.java
----
include::{sourceDir}/bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookCatalogueClientStub.java[]
----

Write a test:

[source,java]
.bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookControllerTest.java
----
include::{sourceDir}/bookrecommendation/src/test/java/example/micronaut/bookrecommendation/BookControllerTest.java[]
----

Edit `application.yml`

[source,yaml]
.bookrecommendation/src/main/resources/application.yml
----
include::{sourceDir}/bookrecommendation/src/main/resources/application.yml[tag=mn]
----

<1> Configure the application name. The app name will be used later in the tutorial.
<2> Configure the app to listen at port 8080

Create a file named `application-test.yml` which is used in the test environment:

[source,yaml]
.bookrecommendation/src/main/resources/application-test.yml
----
include::{sourceDir}/bookrecommendation/src/main/resources/application-test.yml[tag=port]
----

<1> Start the micronaut microservice at a random port when running the tests.